### ISSUE TITLE
Validation fails on PR on demo project with gitdb.exc.BadName

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/ballet#30]
### Description

See https://travis-ci.org/micahjsmith/ballet-ames-demo/jobs/503796033

The TravisPullRequestBuildDiffer should successfully identify the comparison ref

### What I Did

```
$ ./validate.py
[2019-03-08 21:14:06,839] {ballet: log.py:116} INFO - Ballet Validation: checking project structure...
[2019-03-08 21:14:06,849] {ballet: log.py:116} INFO - Collecting file changes...
[2019-03-08 21:14:06,856] {ballet: log.py:116} INFO - Collecting file changes...FAILURE
[2019-03-08 21:14:06,856] {ballet: log.py:116} INFO - Ballet Validation: checking project structure...FAILURE
Traceback (most recent call last):
  File "./validate.py", line 12, in <module>
    ballet.validation.main(ames)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/validation/__init__.py", line 151, in main
    check_project_structure(project)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/funcy/decorators.py", line 38, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/validation/__init__.py", line 26, in log_validation_stage
    return call()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/funcy/flow.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/util/log.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/funcy/decorators.py", line 55, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/validation/__init__.py", line 96, in check_project_structure
    result = validator.validate()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/validation/project_structure.py", line 154, in validate
    collected_changes = self.change_collector.collect_changes()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/validation/project_structure.py", line 62, in collect_changes
    file_diffs = self._collect_file_diffs()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/funcy/decorators.py", line 38, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/funcy/flow.py", line 165, in post_processing
    return func(call())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/funcy/decorators.py", line 55, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/util/log.py", line 146, in wrapper
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/validation/project_structure.py", line 74, in _collect_file_diffs
    file_diffs = self.differ.diff()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/util/git.py", line 26, in diff
    diffs = get_diffs_by_diff_str(self.repo, diff_str)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ballet/util/git.py", line 92, in get_diffs_by_diff_str
    b_obj = repo.rev_parse(b)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/repo/fun.py", line 334, in rev_parse
    obj = name_to_object(repo, rev)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref '.59bc5069f7045071ee153e3280319676f85c71f9' did not resolve to an object
The command "./validate.py" exited with 1.
```

**Comment by micahjsmith** [comment]
In this case, TRAVIS_COMMIT_RANGE had three dots rather than two dots. They actually mean different things. In this case, we probably want to use three dots.

See https://stackoverflow.com/q/7251477
