### ISSUE TITLE
Project engineer-features command fails with no features

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/ballet#32]
* ballet version: 0.5.3-dev (981521d)
* Python version: 3.7
* Operating System: macOS 10.14.3

### Description

In a ballet project with no features ("ames"), ran `ames-engineer-features` at initialization (no features yet). The command fails but it should instead exit gracefully.

### What I Did

```
$ ames-engineer-features data/test data/test
/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/ballet/util/io.py:130: FutureWarning: read_table is deprecated, use read_csv instead.
  return pd.read_table(path, **kwargs)
[2019-03-12 15:43:59,320] {ames.features: log.py:116} INFO - Building features and target...
/Users/micahsmith/workspace/ballet-ames-demo/ames/load_data.py:29: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.                                                
  df = pd.read_csv(source, sep=None)
[2019-03-12 15:44:00,201] {ames.features: log.py:116} INFO - Building features and target...DONE
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/ballet-ames-demo/bin/ames-engineer-features", line 11, in <module>
    load_entry_point('ballet-ames-demo', 'console_scripts', 'ames-engineer-features')()
  File "/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/click/core.py", line 764, in __call__                                 
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/click/core.py", line 717, in main                                     
    rv = self.invoke(ctx)
  File "/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/click/core.py", line 956, in invoke                                   
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/click/core.py", line 555, in invoke                                   
    return callback(*args, **kwargs)
  File "/Users/micahsmith/workspace/ballet-ames-demo/ames/features/__init__.py", line 94, in main
    X_ft = mapper_X.transform(X_df)
  File "/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/sklearn_pandas/dataframe_mapper.py", line 377, in transform           
    return self._transform(X)
  File "/usr/local/miniconda3/envs/ballet-ames-demo/lib/python3.7/site-packages/sklearn_pandas/dataframe_mapper.py", line 292, in _transform          
    for columns, transformers, options in self.built_features:
TypeError: 'NoneType' object is not iterable
```

**Comment by micahjsmith** [comment]
Closed by f4281318edf9874458d2f022bcfb83efe7d9ad91
